# Generated by Django 3.2 on 2021-05-13 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rawdat', '0008_auto_20210513_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('j48', models.DecimalField(decimal_places=8, max_digits=8)),
                ('smo', models.DecimalField(decimal_places=8, max_digits=8)),
                ('lib_linear', models.DecimalField(decimal_places=8, max_digits=8)),
                ('lib_svm', models.DecimalField(decimal_places=8, max_digits=8)),
                ('smo_reg', models.DecimalField(decimal_places=8, max_digits=8)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pww_prediction_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pww_prediction_modified_by', to=settings.AUTH_USER_MODEL)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rawdat.participant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scaled_fastest_time', models.DecimalField(decimal_places=8, max_digits=8)),
                ('win', models.DecimalField(decimal_places=8, max_digits=8)),
                ('place', models.DecimalField(decimal_places=8, max_digits=8)),
                ('show', models.DecimalField(decimal_places=8, max_digits=8)),
                ('break_avg', models.DecimalField(decimal_places=8, max_digits=8)),
                ('eighth_avg', models.DecimalField(decimal_places=8, max_digits=8)),
                ('straight_avg', models.DecimalField(decimal_places=8, max_digits=8)),
                ('finish_avg', models.DecimalField(decimal_places=8, max_digits=8)),
                ('grade_avg', models.DecimalField(decimal_places=8, max_digits=8)),
                ('time_seven', models.DecimalField(decimal_places=8, max_digits=8)),
                ('time_three', models.DecimalField(decimal_places=8, max_digits=8)),
                ('upgrade', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pww_metric_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pww_metric_modified_by', to=settings.AUTH_USER_MODEL)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rawdat.participant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
