# Generated by Django 3.2 on 2021-05-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pww', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='post_factor',
            field=models.DecimalField(decimal_places=8, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='post_weight_avg',
            field=models.DecimalField(decimal_places=8, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='rh_factor',
            field=models.DecimalField(decimal_places=8, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='sex',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='temp_factor',
            field=models.DecimalField(decimal_places=8, max_digits=8, null=True),
        ),
    ]
