# Generated by Django 3.2 on 2021-05-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pww', '0002_auto_20210517_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='break_avg',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='metric',
            name='eighth_avg',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='metric',
            name='finish_avg',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='metric',
            name='grade_avg',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='metric',
            name='place',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='metric',
            name='post_factor',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='rh_factor',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='scaled_fastest_time',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='metric',
            name='show',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='metric',
            name='straight_avg',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='metric',
            name='temp_factor',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='time_seven',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='metric',
            name='time_three',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='metric',
            name='win',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
