# Generated by Django 3.2 on 2021-05-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pww', '0003_auto_20210517_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='post_weight_avg',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
    ]
