# Generated by Django 3.2 on 2021-05-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pww', '0004_alter_metric_post_weight_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='final',
            field=models.IntegerField(null=True),
        ),
    ]
