# Generated by Django 3.2 on 2021-05-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pww', '0005_metric_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='time_seven',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='time_three',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
    ]
