# Generated by Django 3.2 on 2021-05-31 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pww', '0006_auto_20210531_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='grade_avg',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
    ]
