# Generated by Django 3.2 on 2021-06-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pww', '0007_alter_metric_grade_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='straight_avg',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
    ]
