# Generated by Django 3.2 on 2021-06-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pww', '0008_alter_metric_straight_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='j48',
            field=models.DecimalField(decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='lib_linear',
            field=models.DecimalField(decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='lib_svm',
            field=models.DecimalField(decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='smo',
            field=models.DecimalField(decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='smo_reg',
            field=models.DecimalField(decimal_places=8, max_digits=16, null=True),
        ),
    ]
