# Generated by Django 3.2 on 2021-07-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pww', '0013_bet_straightbettype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='straightbettype',
            name='name',
            field=models.CharField(choices=[('P', 'Place'), ('S', 'Show'), ('W', 'Win')], max_length=16),
        ),
    ]
