# Generated by Django 3.2 on 2021-11-09 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rawdat', '0018_alter_participant_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pww', '0016_alter_prediction_j48'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPrediction',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('c', models.DecimalField(decimal_places=8, max_digits=16)),
                ('smo', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pww_testprediction_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pww_testprediction_modified_by', to=settings.AUTH_USER_MODEL)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rawdat.participant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
