# Generated by Django 3.2 on 2021-11-09 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawdat', '0018_alter_participant_options'),
        ('pww', '0017_testprediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testprediction',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawdat.participant'),
        ),
    ]
