# Generated by Django 3.2 on 2021-11-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pww', '0018_alter_testprediction_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='break_avg',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='eighth_avg',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='place',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='scaled_fastest_time',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='show',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='win',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
    ]
