# Generated by Django 3.2 on 2021-11-15 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pww', '0021_alter_prediction_smo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bet_Recommendation',
        ),
    ]
