# Generated by Django 3.2 on 2022-05-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pww', '0022_delete_bet_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediction',
            name='j48',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='lib_linear',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='lib_svm',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='smo',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='smo_reg',
        ),
        migrations.AddField(
            model_name='prediction',
            name='bet',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
