# Generated by Django 3.2 on 2022-05-25 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rawdat', '0025_exotic_scan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pww', '0023_auto_20220516_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='smoreg',
            field=models.DecimalField(decimal_places=8, max_digits=16, null=True),
        ),
        migrations.CreateModel(
            name='BettingGrade',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pww_bettinggrade_created_by', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawdat.grade')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pww_bettinggrade_modified_by', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawdat.venue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
