# Generated by Django 3.2 on 2022-05-26 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pww', '0025_wekaclassifier_wekamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet_Recommendation',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('range_start', models.DecimalField(decimal_places=4, max_digits=8)),
                ('range_end', models.DecimalField(decimal_places=4, max_digits=8)),
                ('bet', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pww_bet_recommendation_created_by', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pww.wekamodel')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pww_bet_recommendation_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='smoreg',
        ),
        migrations.DeleteModel(
            name='TestPrediction',
        ),
        migrations.AddField(
            model_name='prediction',
            name='recommendation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pww.bet_recommendation'),
        ),
    ]
