# Generated by Django 3.2 on 2022-05-30 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawdat', '0039_delete_exotic_bet_type'),
        ('pww', '0028_participant_prediction_smoreg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant_prediction',
            name='bet',
        ),
        migrations.AlterField(
            model_name='participant_prediction',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawdat.participant'),
        ),
    ]
