# Generated by Django 3.2 on 2022-05-31 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawdat', '0040_auto_20220530_2235'),
        ('pww', '0029_auto_20220530_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wekamodel',
            name='betting_grade',
        ),
        migrations.AddField(
            model_name='wekamodel',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rawdat.grade'),
        ),
        migrations.AddField(
            model_name='wekamodel',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rawdat.venue'),
        ),
        migrations.DeleteModel(
            name='BettingGrade',
        ),
    ]
