# Generated by Django 3.2 on 2021-05-03 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BetType',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_bettype_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_bettype_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BetType',
            },
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.CharField(choices=[('A', 'Afternoon'), ('E', 'Evening'), ('S', 'Schooling'), ('T', 'Twilight')], max_length=128)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_chart_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_chart_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chart',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_color_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_color_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Color',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('whelp_date', models.DateField(null=True)),
                ('sex', models.CharField(choices=[('F', 'FEMALE'), ('M', 'MALE')], max_length=1, null=True)),
                ('kennel', models.CharField(max_length=128, null=True)),
                ('trainer', models.CharField(max_length=128, null=True)),
                ('set_weight', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('last_scanned', models.DateTimeField(null=True)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rawdat.color')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_dog_created_by', to=settings.AUTH_USER_MODEL)),
                ('dam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother', to='rawdat.dog')),
            ],
            options={
                'verbose_name': 'Dog',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=3, null=True)),
                ('value', models.IntegerField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_grade_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_grade_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_weight', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('post', models.IntegerField(null=True)),
                ('off', models.IntegerField(null=True)),
                ('eighth', models.IntegerField(null=True)),
                ('straight', models.IntegerField(null=True)),
                ('final', models.IntegerField(null=True)),
                ('lengths_behind', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('actual_running_time', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('comment', models.CharField(max_length=256, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_participant_created_by', to=settings.AUTH_USER_MODEL)),
                ('dog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rawdat.dog')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_participant_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participant',
                'ordering': ['final', 'post'],
            },
        ),
        migrations.CreateModel(
            name='WeatherLookup',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wunderground', models.CharField(max_length=128, null=True)),
                ('code', models.CharField(max_length=128, null=True)),
                ('place', models.CharField(max_length=128, null=True)),
                ('geocode', models.CharField(max_length=128, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_weatherlookup_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_weatherlookup_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True)),
                ('code', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=False)),
                ('street_number', models.CharField(max_length=128, null=True)),
                ('street_name', models.CharField(max_length=128, null=True)),
                ('street_suffix', models.CharField(max_length=128, null=True)),
                ('city', models.CharField(max_length=128, null=True)),
                ('state', models.CharField(max_length=2, null=True)),
                ('zip_code', models.CharField(max_length=24, null=True)),
                ('country', models.CharField(default='USA', max_length=3)),
                ('website', models.CharField(max_length=256, null=True)),
                ('about', models.TextField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_venue_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_venue_modified_by', to=settings.AUTH_USER_MODEL)),
                ('weatherlookup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rawdat.weatherlookup')),
            ],
            options={
                'verbose_name': 'Venue',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('twitter', models.CharField(max_length=128, null=True)),
                ('facebook', models.CharField(max_length=128, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_socialmedia_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_socialmedia_modified_by', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawdat.venue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Single',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_single_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_single_modified_by', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rawdat.participant')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rawdat.bettype')),
            ],
            options={
                'verbose_name': 'DogPayout',
            },
        ),
        migrations.CreateModel(
            name='ScanType',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_scantype_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_scantype_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=256, null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_scan_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_scan_modified_by', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rawdat.scantype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(null=True)),
                ('condition', models.CharField(choices=[('F', 'Fast'), ('L', 'Loose'), ('M', 'Muddy'), ('S', 'Slow'), ('W', 'Wet')], max_length=1, null=True)),
                ('legacy_grade', models.CharField(choices=[('aa', 'AA'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('j', 'J'), ('m', 'M')], max_length=3, null=True)),
                ('is_training', models.BooleanField(default=False)),
                ('distance', models.IntegerField(choices=[(440, '440'), (546, '546'), (550, '550'), (583, '583'), (660, '660')], null=True)),
                ('winning_time', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('chart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rawdat.chart')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_race_created_by', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rawdat.grade')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_race_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Race',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_program_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_program_modified_by', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawdat.venue')),
            ],
            options={
                'verbose_name': 'Program',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='participant',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rawdat.race'),
        ),
        migrations.CreateModel(
            name='Litter',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('whelp_date', models.DateField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_litter_created_by', to=settings.AUTH_USER_MODEL)),
                ('dam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='litter_dam', to='rawdat.dog')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_litter_modified_by', to=settings.AUTH_USER_MODEL)),
                ('sire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='litter_sire', to='rawdat.dog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryScan',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('complete', models.BooleanField(default=False)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_historyscan_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_historyscan_modified_by', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawdat.venue')),
            ],
            options={
                'verbose_name': 'HistoryScan',
            },
        ),
        migrations.AddField(
            model_name='dog',
            name='litter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rawdat.litter'),
        ),
        migrations.AddField(
            model_name='dog',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_dog_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dog',
            name='sire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father', to='rawdat.dog'),
        ),
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_combination_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_combination_modified_by', to=settings.AUTH_USER_MODEL)),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rawdat.race')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rawdat.bettype')),
            ],
            options={
                'verbose_name': 'CombinationPayout',
            },
        ),
        migrations.AddField(
            model_name='chart',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rawdat.program'),
        ),
    ]
