# Generated by Django 3.2 on 2021-05-11 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rawdat', '0003_cronjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exacta',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('payout', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_exacta_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_exacta_modified_by', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exacta_place', to='rawdat.participant')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawdat.race')),
                ('win', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exacta_win', to='rawdat.participant')),
            ],
            options={
                'verbose_name': 'Exacta',
            },
        ),
        migrations.CreateModel(
            name='Quiniela',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('payout', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_quiniela_created_by', to=settings.AUTH_USER_MODEL)),
                ('left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiniela_left', to='rawdat.participant')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_quiniela_modified_by', to=settings.AUTH_USER_MODEL)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawdat.race')),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiniela_right', to='rawdat.participant')),
            ],
            options={
                'verbose_name': 'Quiniela',
            },
        ),
        migrations.CreateModel(
            name='Superfecta',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('payout', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_superfecta_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_superfecta_modified_by', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superfecta_place', to='rawdat.participant')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawdat.race')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superfecta_show', to='rawdat.participant')),
                ('take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superfecta_take', to='rawdat.participant')),
                ('win', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superfecta_win', to='rawdat.participant')),
            ],
            options={
                'verbose_name': 'Superfecta',
            },
        ),
        migrations.CreateModel(
            name='Trifecta',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('payout', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_trifecta_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_trifecta_modified_by', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trifecta_place', to='rawdat.participant')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawdat.race')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trifecta_show', to='rawdat.participant')),
                ('win', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trifecta_win', to='rawdat.participant')),
            ],
            options={
                'verbose_name': 'Trifecta',
            },
        ),
        migrations.AlterModelOptions(
            name='single',
            options={'verbose_name': 'SingleBet'},
        ),
        migrations.RenameField(
            model_name='single',
            old_name='amount',
            new_name='payout',
        ),
        migrations.DeleteModel(
            name='Combination',
        ),
    ]
