# Generated by Django 3.2 on 2021-05-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdat', '0004_auto_20210511_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exacta',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quiniela',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='single',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='superfecta',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trifecta',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=10),
        ),
    ]
