# Generated by Django 3.2 on 2021-05-12 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rawdat', '0005_auto_20210511_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dew_point', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('min_temp', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('mean_temp', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('max_temp', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('mean_rh', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('max_rh', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('percipitation', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('visibility', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('wind', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_weather_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_weather_modified_by', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rawdat.program')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
