# Generated by Django 3.2 on 2021-05-13 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawdat', '0006_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='venue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rawdat.venue'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='weatherlookup',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rawdat.weatherlookup'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='program',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rawdat.program'),
        ),
    ]
