# Generated by Django 3.2 on 2021-05-13 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rawdat', '0007_auto_20210513_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Straight_Wager',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost', models.DecimalField(decimal_places=2, default=2.0, max_digits=10)),
                ('win', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('place', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('show', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_straight_wager_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_straight_wager_modified_by', to=settings.AUTH_USER_MODEL)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rawdat.participant')),
            ],
            options={
                'verbose_name': 'Straight',
            },
        ),
        migrations.RemoveField(
            model_name='single',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='single',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='single',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='single',
            name='type',
        ),
        migrations.AlterField(
            model_name='exacta',
            name='race',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rawdat.race'),
        ),
        migrations.AlterField(
            model_name='quiniela',
            name='race',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rawdat.race'),
        ),
        migrations.AlterField(
            model_name='superfecta',
            name='race',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rawdat.race'),
        ),
        migrations.AlterField(
            model_name='trifecta',
            name='race',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rawdat.race'),
        ),
        migrations.DeleteModel(
            name='BetType',
        ),
        migrations.DeleteModel(
            name='Single',
        ),
    ]
