# Generated by Django 3.2 on 2021-05-14 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawdat', '0008_auto_20210513_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exacta',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawdat.race'),
        ),
        migrations.AlterField(
            model_name='quiniela',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawdat.race'),
        ),
        migrations.AlterField(
            model_name='superfecta',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawdat.race'),
        ),
        migrations.AlterField(
            model_name='trifecta',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawdat.race'),
        ),
    ]
