# Generated by Django 3.2 on 2021-05-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdat', '0010_auto_20210518_0106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cronjob',
            options={'ordering': ['-created_at'], 'verbose_name': 'CronJob'},
        ),
        migrations.AlterField(
            model_name='participant',
            name='actual_running_time',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='lengths_behind',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
    ]
