# Generated by Django 3.2 on 2021-05-31 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdat', '0012_auto_20210529_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='winning_time',
        ),
        migrations.AlterField(
            model_name='weather',
            name='dew_point',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='max_rh',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='max_temp',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='mean_rh',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='mean_temp',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='min_temp',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='percipitation',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='pressure',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='visibility',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
