# Generated by Django 3.2 on 2021-07-20 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawdat', '0015_venue_kiosk_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['-name'], 'verbose_name': 'Venue'},
        ),
    ]
