# Generated by Django 3.2 on 2021-11-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdat', '0019_bet_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet_recommendation',
            name='classifier',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
