# Generated by Django 3.2 on 2022-04-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdat', '0020_bet_recommendation_classifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet_recommendation',
            name='c_factor',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bet_recommendation',
            name='cutoff',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bet_recommendation',
            name='months',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bet_recommendation',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
