# Generated by Django 3.2 on 2022-05-01 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rawdat', '0021_auto_20220428_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedUrl',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=256)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_scannedurl_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_scannedurl_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ScannedUrl',
            },
        ),
    ]
