# Generated by Django 3.2 on 2022-05-16 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawdat', '0023_exacta_wager_quiniela_wager_superfecta_wager_trifecta_wager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiniela_wager',
            options={'verbose_name': 'Quinella'},
        ),
    ]
