# Generated by Django 3.2 on 2022-05-26 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawdat', '0025_exotic_scan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
