# Generated by Django 3.2 on 2022-05-26 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rawdat', '0026_delete_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldTrifecta',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost', models.DecimalField(decimal_places=2, default=2.0, max_digits=10)),
                ('payout', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_oldtrifecta_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_oldtrifecta_modified_by', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trifecta_place', to='rawdat.participant')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawdat.race')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trifecta_show', to='rawdat.participant')),
                ('win', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trifecta_win', to='rawdat.participant')),
            ],
            options={
                'verbose_name': 'Trifecta',
            },
        ),
        migrations.DeleteModel(
            name='Trifecta',
        ),
    ]
