# Generated by Django 3.2 on 2022-05-26 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rawdat', '0027_auto_20220526_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trifecta_wager',
            name='amount',
        ),
        migrations.AddField(
            model_name='trifecta_wager',
            name='wager_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Winning_Trifecta',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payout', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_winning_trifecta_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_winning_trifecta_modified_by', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_trifecta_wager_place', to='rawdat.participant')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawdat.race')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_trifecta_wager_show', to='rawdat.participant')),
                ('win', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_trifecta_wager_win', to='rawdat.participant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
