# Generated by Django 3.2 on 2022-05-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdat', '0031_auto_20220527_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedurl',
            name='comment',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='scannedurl',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
