# Generated by Django 3.2 on 2022-05-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawdat', '0032_auto_20220527_0145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='condition',
            new_name='legacy_condition',
        ),
    ]
