# Generated by Django 3.2 on 2022-05-28 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rawdat', '0034_rename_new_condition_race_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant_Prediction',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bets', models.CharField(max_length=16)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_participant_prediction_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_participant_prediction_modified_by', to=settings.AUTH_USER_MODEL)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rawdat.participant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sizzle_Exacta',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_sizzle_exacta_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_sizzle_exacta_modified_by', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizzle_exacta_place', to='rawdat.participant')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawdat.race')),
                ('win', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizzle_exacta_win', to='rawdat.participant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sizzle_Quinella',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_sizzle_quinella_created_by', to=settings.AUTH_USER_MODEL)),
                ('left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizzle_quinella_left', to='rawdat.participant')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_sizzle_quinella_modified_by', to=settings.AUTH_USER_MODEL)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawdat.race')),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizzle_quinella_right', to='rawdat.participant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sizzle_Superfecta',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_sizzle_superfecta_created_by', to=settings.AUTH_USER_MODEL)),
                ('fourth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizzle_superfecta_fourth', to='rawdat.participant')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_sizzle_superfecta_modified_by', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizzle_superfecta_place', to='rawdat.participant')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawdat.race')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizzle_superfecta_show', to='rawdat.participant')),
                ('win', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizzle_superfecta_win', to='rawdat.participant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sizzle_Trifecta',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_sizzle_trifecta_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_sizzle_trifecta_modified_by', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizzle_trifecta_place', to='rawdat.participant')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawdat.race')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizzle_trifecta_show', to='rawdat.participant')),
                ('win', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizzle_trifecta_win', to='rawdat.participant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Straight_Bet',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_straight_bet_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_straight_bet_modified_by', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawdat.participant')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawdat.straightbettype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trifecta_Prediction',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wager_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_trifecta_prediction_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdat_trifecta_prediction_modified_by', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trifecta_wager_place', to='rawdat.participant')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trifecta_wager', to='rawdat.race')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trifecta_wager_show', to='rawdat.participant')),
                ('win', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trifecta_wager_win', to='rawdat.participant')),
            ],
            options={
                'verbose_name': 'Trifecta',
            },
        ),
        migrations.DeleteModel(
            name='Predicted_Trifecta',
        ),
    ]
