# Generated by Django 3.2 on 2022-05-28 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawdat', '0036_delete_participant_prediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superfecta_wager',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='superfecta_wager',
            name='fourth',
        ),
        migrations.RemoveField(
            model_name='superfecta_wager',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='superfecta_wager',
            name='place',
        ),
        migrations.RemoveField(
            model_name='superfecta_wager',
            name='race',
        ),
        migrations.RemoveField(
            model_name='superfecta_wager',
            name='show',
        ),
        migrations.RemoveField(
            model_name='superfecta_wager',
            name='win',
        ),
        migrations.RemoveField(
            model_name='trifecta_prediction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='trifecta_prediction',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='trifecta_prediction',
            name='place',
        ),
        migrations.RemoveField(
            model_name='trifecta_prediction',
            name='race',
        ),
        migrations.RemoveField(
            model_name='trifecta_prediction',
            name='show',
        ),
        migrations.RemoveField(
            model_name='trifecta_prediction',
            name='win',
        ),
        migrations.DeleteModel(
            name='Exacta_Wager',
        ),
        migrations.DeleteModel(
            name='Superfecta_Wager',
        ),
        migrations.DeleteModel(
            name='Trifecta_Prediction',
        ),
    ]
