# Generated by Django 3.2 on 2022-05-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdat', '0037_auto_20220528_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizzle_exacta',
            name='place',
        ),
        migrations.RemoveField(
            model_name='sizzle_exacta',
            name='win',
        ),
        migrations.RemoveField(
            model_name='sizzle_quinella',
            name='left',
        ),
        migrations.RemoveField(
            model_name='sizzle_quinella',
            name='right',
        ),
        migrations.RemoveField(
            model_name='sizzle_superfecta',
            name='fourth',
        ),
        migrations.RemoveField(
            model_name='sizzle_superfecta',
            name='place',
        ),
        migrations.RemoveField(
            model_name='sizzle_superfecta',
            name='show',
        ),
        migrations.RemoveField(
            model_name='sizzle_superfecta',
            name='win',
        ),
        migrations.RemoveField(
            model_name='sizzle_trifecta',
            name='place',
        ),
        migrations.RemoveField(
            model_name='sizzle_trifecta',
            name='show',
        ),
        migrations.RemoveField(
            model_name='sizzle_trifecta',
            name='win',
        ),
        migrations.AddField(
            model_name='sizzle_exacta',
            name='place_post',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sizzle_exacta',
            name='win_post',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sizzle_quinella',
            name='left_post',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sizzle_quinella',
            name='right_post',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sizzle_superfecta',
            name='fourth_post',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sizzle_superfecta',
            name='place_post',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sizzle_superfecta',
            name='show_post',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sizzle_superfecta',
            name='win_post',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sizzle_trifecta',
            name='place_post',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sizzle_trifecta',
            name='show_post',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sizzle_trifecta',
            name='win_post',
            field=models.IntegerField(null=True),
        ),
    ]
