# Generated by Django 3.2 on 2022-05-30 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawdat', '0038_auto_20220528_0735'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exotic_Bet_Type',
        ),
    ]
